Add MockTools for testing HTTP1ConnectionPool.StateMachine
swift-server/async-http-client pull request #417
Opened 2021-09-07 10:04 UTC by fabianfett

2021-09-07 11:00 UTC, Lukasa requested changes

2021-09-07 11:11 UTC, glbrntt commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +                }
Do we need to transition to `closed` here on the happy path?

2021-09-07 11:11 UTC, glbrntt commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +            .sorted(by: { $0.lastIdle! > $1.lastIdle! })
This is redundant with the `max(by:)` below
```suggestion
```

2021-09-07 11:11 UTC, glbrntt commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +            throw Errors.connectionIDAlreadyUsed
do we really need to distinguish this from `Errors.connectionExists`?

2021-09-07 11:11 UTC, glbrntt commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +    mutating func randomStartingConnection() -> Connection.ID? {
These are all for the fuzzing, presumably? Might be worth sticking them in an extension.

2021-09-07 13:07 UTC, fabianfett commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +        enum State {
We could make this `Hashable`, but TBH really his should be private. So the benefit of it being `Hashable` is not very large. :)

2021-09-08 08:18 UTC, glbrntt commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +        enum State {
Agreed, it isn't large. I was thinking along the lines of killing some of the `switch`es in the various `is<State>` computed properties.

2021-09-08 08:29 UTC, glbrntt approved these changes
Looks good aside from a couple of trivial things

2021-09-08 08:29 UTC, glbrntt commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +                if used + 1 > maxStreams {
Seems odd to do the addition twice.
```suggestion
                if used >= maxStreams {
```

2021-09-08 08:29 UTC, glbrntt commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +    var leased: Int {
Should this be `used` now?

2021-09-08 08:29 UTC, glbrntt commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +    mutating func randomStartingConnection() -> Connection.ID? {
Why are the `random<State>Connection` functions `mutating`?

2021-09-08 08:47 UTC, Lukasa requested changes

2021-09-08 08:47 UTC, Lukasa commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +                if maxStreams < 1 {
I don't think this state is real: a HTTP/2 connection is not allowed to have max streams less than 1.

2021-09-08 08:47 UTC, Lukasa commented on Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
> +                    self.state = .http2(.inUse(maxConcurrentStreams: maxStreams, used: used))
Shouldn't `used` be decremented here?

2021-09-08 15:44 UTC, Lukasa approved these changes

2021-09-08 15:45 UTC, merged