Update async usages in README and examples to shutdown properly
swift-server/async-http-client pull request #727
Opened 2024-01-23 03:46 UTC by michaelmcguire

Motivation:

In several examples of async/await support, the call to shutdown() on the HTTPClient are made with await but do not call get() on the EventLoopFuture.

Modifications:

Add the .get() call in four locations that need it.

Result:

After fixing this, the client should properly get closed down and there are no longer warnings emitted by the compiler.

2024-01-23 14:30 UTC, FranzBusch approved these changes

2024-01-23 14:33 UTC, dnadoba commented
@swift-server-bot test this please

2024-01-23 14:39 UTC, dnadoba requested changes
There is a [`shutdown()`  that is async](https://github.com/swift-server/async-http-client/blob/09b7eb751e297396f44b270b26754f9c85b105d1/Sources/AsyncHTTPClient/AsyncAwait/HTTPClient%2Bshutdown.swift#L20) and needs to be awaited. I'm not sure why you are seeing the warnings. Can you please post the exact warning you are seeing? Do you have a reproducer?

2025-01-03 20:00 UTC, michaelmcguire commented
Sorry for the long delay on this. I will double-check and open again if I hit this.

2025-01-03 20:00 UTC, closed without merging